import type { Tables } from './database.types'

// ============================================================
// Hand-written union types — these mirror Postgres CHECK constraints
// from migrations and are NOT regenerated by `supabase gen types`.
// Keep in sync with the corresponding migration when extending.
// ============================================================

export type UserRole =
  | 'super_admin'
  | 'company_admin'
  | 'dispatcher'
  | 'comptable'
  | 'driver'
  | 'client'
  | 'external_accountant'

export type ShipmentStatus =
  | 'created'
  | 'assigned'
  | 'picked_up'
  | 'in_transit'
  | 'customs_clearance'
  | 'delivered'
  | 'failed'
  | 'cancelled'

export type InvoiceStatus =
  | 'unpaid'
  | 'partially_paid'
  | 'paid'
  | 'overdue'
  | 'cancelled'

export type BillingMode = 'per_shipment' | 'monthly_grouped'

export type VehicleType = 'motorcycle' | 'van' | 'truck' | 'pickup'

export type NotificationChannel = 'email' | 'whatsapp' | 'sms'
export type NotificationStatus = 'pending' | 'sent' | 'failed' | 'skipped'

export type AccountantDeliveryMethod = 'email' | 'usb' | 'paper' | 'portal'

export type MonthlyDossierStatus =
  | 'in_progress'
  | 'ready'
  | 'sent'
  | 'closed_by_accountant'

// Mirrors the CHECK constraint on accounting_documents.document_category
// from migration 20260430120000_accounting_documents.sql.
export type AccountingDocumentCategory =
  | 'invoice_client'
  | 'invoice_supplier'
  | 'fuel_receipt'
  | 'toll_receipt'
  | 'maintenance_receipt'
  | 'driver_advance'
  | 'salary_slip'
  | 'cnss_payment'
  | 'ir_payment'
  | 'phone_internet'
  | 'office_rent'
  | 'insurance'
  | 'bank_statement'
  | 'bank_fee'
  | 'other'

// Mirrors the CHECK constraint on accounting_documents.status.
export type AccountingDocumentStatus =
  | 'pending_review'
  | 'validated'
  | 'sent_to_accountant'
  | 'rejected'
  | 'archived'

export type AccountingFileType = 'pdf' | 'image' | 'scanned'

export type AccountingPaymentMethod = 'cash' | 'transfer' | 'check' | 'card'

export type AccountingAuditAction =
  | 'create'
  | 'update'
  | 'validate'
  | 'reject'
  | 'complete'
  | 'delete'
  | 'send'
  | 'archive'

export type AccountingAuditEntity =
  | 'accounting_document'
  | 'monthly_dossier'
  | 'tax_declaration'
  | 'payroll_data'
  | 'accountant_profile'
  | 'subcontracted_mission'
  | 'subcontractor'
  | 'client_jit_policy'
  | 'shipment_customs_document'
  | 'free_zone'
  | 'customs_document_type'
  | 'recurring_schedule'
  | 'cmr_document'
  | 'whatsapp_template'
  | 'whatsapp_send'
  | 'supplier'
  | 'supplier_invoice'
  | 'supplier_payment'
  | 'vehicle_pass'
  | 'toll_transaction'
  | 'vignette'
  | 'external_accountant_action'

export type CmrStatus = 'draft' | 'issued' | 'signed' | 'cancelled'
export type CmrPayer = 'sender' | 'consignee' | 'split'

export type TaxDeclarationType = 'vat' | 'ir' | 'cnss'
export type TaxDeclarationStatus = 'pending' | 'declared' | 'paid' | 'overdue'

export type PayrollStatus = 'draft' | 'validated' | 'paid'

export type ClientContractStatus = 'active' | 'expired' | 'cancelled' | 'draft'
export type ClientContractBillingMode = 'per_shipment' | 'monthly_grouped'

export type BlFieldType =
  | 'text'
  | 'number'
  | 'date'
  | 'time'
  | 'select'
  | 'checkbox'
  | 'textarea'

export type RecurringScheduleVehicleType = 'motorcycle' | 'van' | 'truck' | 'pickup'

export type SubcontractedMissionStatus =
  | 'draft'
  | 'sent'
  | 'accepted'
  | 'in_progress'
  | 'completed'
  | 'cancelled'

export type WhatsappAudience = 'driver' | 'client' | 'subcontractor' | 'internal'

export type SupplierCategory =
  | 'fuel'
  | 'parts'
  | 'garage'
  | 'tires'
  | 'insurance'
  | 'telecom'
  | 'office'
  | 'cleaning'
  | 'other'

export type SupplierInvoiceStatus =
  | 'unpaid'
  | 'partially_paid'
  | 'paid'
  | 'overdue'
  | 'cancelled'

export type PassProvider = 'jawaz' | 'passplus' | 'autre'
export type TollKind = 'crossing' | 'top_up' | 'adjustment'
export type VignetteKind =
  | 'annual'
  | 'technical_inspection'
  | 'insurance'
  | 'tax_disc'
  | 'other'

// Authenticated user profile (from public.users joined with auth.users)
export interface AuthUser {
  id: string
  email: string
  companyId: string | null
  role: UserRole
  fullName: string
  preferredLanguage: 'fr' | 'ar'
  avatarUrl: string | null
  isActive: boolean
}

// Server action standard response
export type ActionResult<T = null> =
  | { data: T; error: null }
  | { data: null; error: string }

// Shipment with joined relations (for list/detail views)
export type ShipmentWithRelations = Tables<'shipments'> & {
  client: Pick<Tables<'clients'>, 'id' | 'business_name' | 'contact_name' | 'contact_phone'> | null
  driver: Pick<Tables<'drivers'>, 'id' | 'full_name' | 'phone' | 'avatar_url'> | null
  vehicle: Pick<Tables<'vehicles'>, 'id' | 'plate_number' | 'brand' | 'model' | 'type'> | null
  documents?: Tables<'shipment_documents'>[]
  status_history?: Tables<'shipment_status_history'>[]
}

// Invoice with joined relations
export type InvoiceWithRelations = Tables<'invoices'> & {
  client: Pick<Tables<'clients'>, 'id' | 'business_name' | 'contact_name' | 'contact_email'> | null
  shipments?: Tables<'shipments'>[]
  payments?: Tables<'invoice_payments'>[]
}

// Driver with current vehicle
export type DriverWithVehicle = Tables<'drivers'> & {
  current_vehicle: Pick<Tables<'vehicles'>, 'id' | 'plate_number' | 'brand' | 'model' | 'type'> | null
}

// Pricing rates (from contract or defaults)
export interface PricingRates {
  baseFee: number
  pricePerKm: number
  urgencySurchargePct: number
  vatRate: number
  contractId: string | null
  source: 'contract' | 'default'
}

// Pricing calculation result
export interface PriceBreakdown {
  distanceKm: number
  baseFee: number
  distanceCost: number
  urgencySurcharge: number
  priceExclTax: number
  vatRate: number
  taxAmount: number
  priceInclTax: number
  isUrgent: boolean
  rates: PricingRates
}

// Mapbox geocoding result
export interface GeocodingResult {
  lat: number
  lng: number
  street: string
  city: string
  postalCode: string | null
  region: string | null
  country: string
  formattedAddress: string
}

// Route distance from Mapbox Directions API
export interface RouteResult {
  distanceKm: number
  durationMin: number
}

// Dashboard KPIs
export interface ShipmentKPIs {
  shipmentsToday: number
  shipmentsThisWeek: number
  shipmentsThisMonth: number
  activeShipments: number
  deliveredThisMonth: number
  onTimeRatePct: number | null
  revenueThisMonth: number
}

// Filter types for lists
export interface ShipmentFilters {
  status?: string[]
  clientId?: string
  driverId?: string
  dateFrom?: string
  dateTo?: string
  search?: string
}

export interface InvoiceFilters {
  status?: string[]
  clientId?: string
  dateFrom?: string
  dateTo?: string
}
